# Generated by Django 3.1.2 on 2020-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('box_number', models.CharField(max_length=100)),
                ('article_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('record_time', models.TimeField()),
                ('registration_date', models.DateField()),
                ('due_date', models.DateField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
