# Generated by Django 3.1.2 on 2020-10-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='amount',
            new_name='total_boxes',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='article_name',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='box_number',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='record_time',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='username',
        ),
    ]
