# Generated by Django 3.1.2 on 2020-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0002_auto_20201004_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='pallet_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
