# Generated by Django 3.1.2 on 2020-10-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pallets', '0002_auto_20201004_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('box_number', models.CharField(max_length=100)),
                ('article_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('record_time', models.TimeField()),
                ('registration_date', models.DateField()),
                ('due_date', models.DateField()),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pallets.pallet')),
            ],
        ),
    ]
